const SHEET_CONFIG = {
  spreadsheetId: "1PfwZpYRf6wBvcuCVZIfsUjxreO5Q8A_-OWbZJH3YRnk",
  tabs: {
    miles: "Miles",
    cashback: "Cashback",
  },
};

const FALLBACK_CARDS = {
  miles: [
    {
      card_name: "HSBC Revolution Credit Card",
      bank: "HSBC",
      earn_rate: "Up to 4 mpd on eligible online/contactless spend; up to 8 mpd with qualifying HSBC EGA relationship.",
      use_card_for: "Dining, shopping, travel, ride-hailing, taxis, memberships and selected online/contactless everyday spend.",
      online_or_offline: "Online + contactless, but only for HSBC-listed bonus categories.",
      monthly_bonus_limit: "4 mpd: bonus cap is equivalent to S$1,000 eligible spend per calendar month. 8 mpd Enhanced setup has a 22,800 bonus points cap per calendar month, about S$1,200 eligible spend; verify HSBC EGA conditions.",
      cap_period: "Calendar month / HSBC qualifying posting basis.",
      minimum_spend: "No ordinary minimum spend for 4 mpd; EGA boost requires qualifying HSBC Everyday Global Account balance.",
      nuances: "MCC-sensitive. HSBC miles transfer ratio is less straightforward than Citi/DBS/UOB. EGA boost makes this much stronger but adds deposit/admin complexity.",
      important_exclusions: "Commonly excluded or risky: insurance premiums, school/tuition fees, donations, government/tax payments, financial institutions, quasi-cash, securities/crypto, stored-value or e-wallet top-ups, utilities/bill payments, professional services and any merchant outside HSBC's selected bonus categories.",
      definitions_examples: "Selected online spend means the merchant/acquirer processes it as an online transaction and it falls in HSBC's eligible categories. Contactless spend means tap-to-pay at a terminal, e.g. Visa payWave / mobile tap. Do not confuse contactless payment with topping up an e-wallet app; top-ups are usually excluded.",
      simple_notes: "Use as a clean starter card for eligible online/contactless spend. Good for dining, shopping and travel-related categories when the merchant qualifies.",
      recommendation_tier: "Core starter / flexible online-contactless",
      card_id: "hsbc-revolution",
      network: "Visa Signature",
      category: "Miles",
      status: "Active recommendation",
      base_earn_rate: "Base points apply outside bonus eligibility.",
      rewards_currency: "HSBC Reward points",
      expiry_or_crediting: "Base points credited by statement cycle; bonus points by last day of following calendar month.",
      recommended_pairings: "Pair with Citi Rewards or DBS Woman's World for online overflow; UOB Preferred Visa for mobile contactless clarity.",
      official_product_url: "https://www.hsbc.com.sg/credit-cards/products/revolution/",
      official_terms_url: "https://www.hsbc.com.sg/content/dam/hsbc/sg/documents/credit-cards/revolution/offers/revolution-credit-card-reward-points-terms-and-conditions.pdf",
      official_rewards_or_exclusions_url: "https://www.hsbc.com.sg/credit-cards/products/revolution/",
      research_reference_1: "https://milelion.com/2026/03/16/wow-hsbc-revolution-enhances-earn-rate-to-8-mpd-permanently-restores-travel-and-contactless-bonuses/",
      research_reference_2: "https://suitesmile.com/blog/2026/04/08/hsbc-revolution-card-review/",
      last_verified: "2026-05-29",
      data_confidence: "High; official HSBC page and reward points terms reviewed 2026-05-29.",
      site_tags: "starter,online,contactless,dining,travel,hsbc-ega",
    },
    {
      card_name: "Citi Rewards Card",
      bank: "Citibank",
      earn_rate: "4 mpd via 10X Citi ThankYou Points on eligible online spend.",
      use_card_for: "Online shopping, food delivery, ride-hailing and many app/website payments that are not travel or excluded wallet transactions.",
      online_or_offline: "Online only for bonus earn.",
      monthly_bonus_limit: "9,000 Bonus Points cap per statement month, equivalent to S$1,000 eligible 10X online spend.",
      cap_period: "Statement month.",
      minimum_spend: "None for ordinary 10X earning.",
      nuances: "Very useful online card, but Citi excludes travel-related transactions and mobile wallet transactions from 10X. Watch statement-month timing.",
      important_exclusions: "Commonly excluded or risky: flights, hotels, travel agencies/OTAs, cruises and other travel-related MCCs; mobile wallet transactions; GrabPay/e-wallet top-ups; tax/government, insurance, education, utilities, financial/quasi-cash, crypto/securities and bill-payment platforms.",
      definitions_examples: "Online spend means the merchant is processed as e-commerce. Citi Rewards specifically excludes mobile wallet transactions, so in-app wallet routes such as Apple Pay/Google Pay in-app, GrabPay, Amaze/CardUp-style intermediary payments, or wallet top-ups should be treated as risky/excluded. Offline Apple Pay/Google Pay tap is not the intended 4 mpd use case for this card.",
      simple_notes: "Use this for online retail, food delivery and ride-hailing. Do not default to it for flights, hotels or travel portals.",
      recommendation_tier: "Online shopping workhorse",
      card_id: "citi-rewards",
      network: "Mastercard",
      category: "Miles",
      status: "Active recommendation",
      base_earn_rate: "1X Citi ThankYou Point per S$1 on eligible base spend.",
      rewards_currency: "Citi ThankYou Points",
      expiry_or_crediting: "Subject to Citi ThankYou Rewards programme terms.",
      recommended_pairings: "Pair with DBS Woman's World for broader online travel-type transactions; avoid using for excluded mobile-wallet routes.",
      official_product_url: "https://www.citibank.com.sg/credit-cards/rewards/citi-rewards-card/",
      official_terms_url: "https://www.citibank.com.sg/credit-cards/rewards/citi-rewards-card/pdf/10x-rewards-promotion-terms-and-conditions-2020.pdf",
      official_rewards_or_exclusions_url: "https://www.citibank.com.sg/gcb/static/products_tncs",
      research_reference_1: "https://milelion.com/2025/05/27/review-citi-rewards-credit-card/",
      research_reference_2: "https://suitesmile.com/blog/2026/01/23/citi-rewards-card-review-best-miles-card/",
      last_verified: "2026-05-29",
      data_confidence: "High; official Citi card page and 10X terms reviewed 2026-05-29.",
      site_tags: "online,shopping,food-delivery,ride-hailing,citi",
    },
    {
      card_name: "DBS Woman's World Card",
      bank: "DBS",
      earn_rate: "4 mpd via 10X DBS Points on online spend; overseas spend earns 3X DBS Points (1.2 mpd) unless otherwise bonused.",
      use_card_for: "Broad online spend, e-commerce, online travel bookings and many website/app transactions.",
      online_or_offline: "Online mainly; useful for overseas online spend depending on DBS rules.",
      monthly_bonus_limit: "S$1,000 eligible online spend per calendar month.",
      cap_period: "Calendar month.",
      minimum_spend: "None for bonus rate, subject to eligibility and caps.",
      nuances: "Good broad online card, but DBS Points from this card are short-expiry and the income requirement is higher than mass-market cards.",
      important_exclusions: "Commonly excluded or risky: transactions DBS does not recognise as online retail, cash advances, balance/fund transfers, fees/charges, tax/government, insurance, education, utilities, top-ups, financial/quasi-cash, securities/crypto and other DBS rewards exclusions.",
      definitions_examples: "Online purchase means the transaction is processed by the merchant/acquirer as online. Website/app checkout is usually the intended use; physical tap/in-store spend normally is not. Online travel can work better here than Citi Rewards, but still depends on DBS bonus rules and merchant coding.",
      simple_notes: "Use this for online spend where Citi Rewards is excluded, especially online travel-style transactions if DBS awards bonus points.",
      recommendation_tier: "Broad online spend card",
      card_id: "dbs-womans-world",
      network: "Mastercard",
      category: "Miles",
      status: "Active recommendation",
      base_earn_rate: "1X DBS Point per S$5 local spend and 3X DBS Points per S$5 overseas spend, unless bonus applies.",
      rewards_currency: "DBS Points",
      expiry_or_crediting: "DBS Points from Woman's World are generally short-expiry; verify current DBS rewards terms before redemption planning.",
      recommended_pairings: "Pair with Citi Rewards for online cap stacking; use UOB Preferred Visa or Visa Signature for offline mobile contactless.",
      official_product_url: "https://www.dbs.com.sg/personal/cards/credit-cards/dbs-woman-mastercard-card",
      official_terms_url: "https://www.dbs.com.sg/personal/cards/cards-terms-conditions.page",
      official_rewards_or_exclusions_url: "https://www.dbs.com.sg/personal/cards/cards-faqs.page",
      research_reference_1: "https://milelion.com/2025/08/09/review-dbs-womans-world-card/",
      research_reference_2: "https://mainlymiles.com/2025/08/07/dbs-wwmc-review-2025/",
      last_verified: "2026-05-29",
      data_confidence: "High; official DBS product page reviewed 2026-05-29.",
      site_tags: "online,travel,ecommerce,dbs,high-income",
    },
    {
      card_name: "UOB Lady's Card",
      bank: "UOB",
      earn_rate: "4 mpd via UNI$10 per S$5 on one selected bonus category.",
      use_card_for: "One chosen category: Fashion, Dining, Travel, Beauty & Wellness, Family, Transport or Entertainment.",
      online_or_offline: "Depends on selected category; can be online or offline if the MCC qualifies.",
      monthly_bonus_limit: "S$1,000 selected-category spend per calendar month for UOB Lady's Card; Solitaire / Lady's Solitaire Metal variants have different caps.",
      cap_period: "Calendar month.",
      minimum_spend: "None for base selected-category earn; savings boost has separate deposit criteria.",
      nuances: "Choose/change category quarterly. UOB awards points in S$5 blocks, so small odd-amount transactions can lose value. Category is MCC-sensitive.",
      important_exclusions: "Commonly excluded or risky: spend outside the chosen category, wrong MCC despite looking similar to the category, top-ups, quasi-cash, tax/government, insurance, utilities, education, hospitals/medical, financial institutions, crypto/securities and other UOB excluded transactions.",
      definitions_examples: "Selected category is MCC-based, not based on what the shop feels like. Example: a cafe inside a hotel, supermarket marketplace seller, or Taobao merchant may code differently. UOB generally awards UNI$ in S$5 blocks, so small odd-amount transactions can earn less than expected.",
      simple_notes: "Use this as the dedicated card for the client's biggest monthly category, e.g. dining, family/groceries, transport or travel.",
      recommendation_tier: "Choose-one-category optimiser",
      card_id: "uob-ladys",
      network: "Mastercard",
      category: "Miles",
      status: "Active recommendation",
      base_earn_rate: "UNI$1 per S$5 on other eligible spend.",
      rewards_currency: "UNI$",
      expiry_or_crediting: "Bonus UNI$ credited per UOB terms; UNI$ expiry applies.",
      recommended_pairings: "Use as the deliberate category card beside Citi Rewards / DBS Woman's World / UOB Preferred Visa.",
      official_product_url: "https://www.uob.com.sg/ladys",
      official_terms_url: "https://www.uob.com.sg/assets/pdfs/ladys-cards-tcs.pdf",
      official_rewards_or_exclusions_url: "https://www.uob.com.sg/personal/cards/rewards/ladys-card/index.page",
      research_reference_1: "https://milelion.com/2026/03/09/uob-ladys-card-lucky-draw-win-76000-bonus-miles-or-s500-gift-cards/",
      research_reference_2: "https://suitesmile.com/best-miles-credit-cards-singapore/",
      last_verified: "2026-05-29",
      data_confidence: "Medium-high; selected-category cap wording should be rechecked against UOB card-specific T&Cs before client advice.",
      site_tags: "category,dining,family,travel,transport,uob",
    },
    {
      card_name: "UOB Preferred Visa Card",
      bank: "UOB",
      earn_rate: "4 mpd via UNI$10 per S$5 on selected online transactions and mobile contactless transactions.",
      use_card_for: "Mobile contactless payments, selected online shopping/entertainment and SimplyGo where eligible.",
      online_or_offline: "Offline via mobile contactless; selected online transactions also qualify.",
      monthly_bonus_limit: "From 1 Oct 2025: bonus UNI$ cap is UNI$1,080 per category per calendar month, about S$600 selected online plus S$600 mobile contactless, or S$1,200 total if both buckets are used.",
      cap_period: "Calendar month.",
      minimum_spend: "No minimum spend for bonus earn under current terms.",
      nuances: "Must use mobile wallet/contactless for the contactless bucket, not physical card tap. UOB awards points in S$5 blocks. Selected online and mobile contactless now have separate monthly sub-caps.",
      important_exclusions: "Commonly excluded or risky: tapping the physical card, non-selected online merchants, in-app wallet/top-up transactions, GrabPay/e-wallet top-ups, tax/government, insurance, education, utilities, hospitals/medical, financial institutions, quasi-cash, crypto/securities and other UOB exclusions.",
      definitions_examples: "Mobile contactless means adding the card to Apple Pay/Google Pay/Samsung Pay or another approved mobile wallet and tapping the phone/watch at a Visa contactless reader. Physical card Visa payWave is not the same for this card. Online transactions qualify only if they fall within UOB's selected online categories.",
      simple_notes: "Use this as the default offline Apple Pay/Google Pay card for everyday contactless spend. Also useful for selected online merchants.",
      recommendation_tier: "Mobile contactless default",
      card_id: "uob-preferred-visa",
      network: "Visa",
      category: "Miles",
      status: "Active recommendation",
      base_earn_rate: "UNI$1 per S$5 on other eligible spend.",
      rewards_currency: "UNI$",
      expiry_or_crediting: "Bonus UNI$ governed by UOB Preferred Visa terms.",
      recommended_pairings: "Pair with UOB Visa Signature for larger contactless/overseas buckets or with UOB Lady's for category spend.",
      official_product_url: "https://www.uob.com.sg/personal/cards/rewards/preferred-visa-card.page",
      official_terms_url: "https://www.uob.com.sg/web-resources/personal/pdf/personal/cards/credit-cards/rewards-cards/uob-preferred-platinum-visa-card/terms-and-conditions-for-preferred-plat-visa.pdf",
      official_rewards_or_exclusions_url: "https://www.uob.com.sg/personal/cards/card-privileges/uob-dollar.page",
      research_reference_1: "https://milelion.com/2026/03/29/review-uob-preferred-platinum-visa-card/",
      research_reference_2: "https://suitesmile.com/blog/2026/03/10/uob-preferred-visa-card-refresh-new-name-new-look/",
      last_verified: "2026-05-29",
      data_confidence: "High; official UOB Preferred Visa page and 2026 MileLion interpretation reviewed 2026-05-29.",
      site_tags: "mobile-contactless,online,simplygo,uob,everyday",
    },
    {
      card_name: "UOB Visa Signature Card",
      bank: "UOB",
      earn_rate: "4 mpd via UNI$10 per S$5 on overseas foreign-currency spend and qualifying local petrol/contactless spend.",
      use_card_for: "Overseas foreign-currency transactions, local petrol, larger local contactless spend and SimplyGo where eligible.",
      online_or_offline: "Offline contactless + overseas online/offline depending on category rules.",
      monthly_bonus_limit: "Approx. S$1,200 spend cap per category bucket per statement period, after meeting S$1,000 minimum in that same category bucket.",
      cap_period: "Statement period.",
      minimum_spend: "S$1,000 minimum spend in the relevant category bucket.",
      nuances: "Threshold card: if the client misses S$1,000 in the bucket, earn rate drops. UOB awards points in S$5 blocks. Good only when spend is high enough.",
      important_exclusions: "Commonly excluded or risky: missing the S$1,000 minimum in the relevant bucket, non-contactless transactions, non-petrol MCCs for petrol bucket, SGD overseas/foreign-gateway ambiguity, top-ups, quasi-cash, tax/government, insurance, utilities, hospitals/medical, financial institutions and other UOB exclusions.",
      definitions_examples: "Contactless includes Visa payWave using the physical card or approved mobile wallet tap at a Visa payWave reader. UOB's terms also treat SimplyGo ABT as contactless under current rules. Magnetic Secure Transmission and non-contactless payment flows are excluded.",
      simple_notes: "Use for bigger contactless months, petrol, or overseas spend when the client can confidently cross the S$1,000 bucket minimum.",
      recommendation_tier: "Higher-cap contactless / overseas card",
      card_id: "uob-visa-signature",
      network: "Visa Signature",
      category: "Miles",
      status: "Active recommendation",
      base_earn_rate: "UNI$1 per S$5 on other eligible spend.",
      rewards_currency: "UNI$",
      expiry_or_crediting: "Bonus UNI$ credited in following statement period.",
      recommended_pairings: "Use after UOB Preferred Visa cap or for overseas spend; not ideal for low-spend clients.",
      official_product_url: "https://www.uob.com.sg/personal/cards/rewards/visa-signature-card.page",
      official_terms_url: "https://www.uob.com.sg/web-resources/personal/pdf/personal/cards/credit-cards/travel-cards/uob-visa-signature-card/terms-and-conditions-governing-uob-visa-signature-card.pdf",
      official_rewards_or_exclusions_url: "https://www.uob.com.sg/personal/cards/card-privileges/uob-dollar.page",
      research_reference_1: "https://milelion.com/2025/08/29/review-uob-visa-signature-card/",
      research_reference_2: "https://suitesmile.com/best-uob-credit-cards-in-singapore/",
      last_verified: "2026-05-29",
      data_confidence: "High; official UOB Visa Signature terms reviewed 2026-05-29.",
      site_tags: "contactless,overseas,petrol,simplygo,uob,higher-cap",
    },
    {
      card_name: "KrisFlyer UOB Credit Card",
      bank: "UOB",
      earn_rate: "3 mpd on SIA/Scoot/KrisShop/Kris+/Pelago; 2.4 mpd on selected categories after S$1,000 annual SIA Group spend; 1.2 mpd general.",
      use_card_for: "SIA Group spend, dining, food delivery, online shopping, online travel and transport.",
      online_or_offline: "Online + offline depending on category.",
      monthly_bonus_limit: "No 4 mpd cap because this is not a 4 mpd specialised card; headline bonus categories are generally uncapped, subject to UOB terms.",
      cap_period: "Card year / annual qualification for accelerated categories.",
      minimum_spend: "S$1,000 annual qualifying SIA Group related spend, specifically Singapore Airlines / Scoot / KrisShop per UOB page, to unlock accelerated everyday categories.",
      nuances: "Direct KrisFlyer miles, simple to understand, but lower than 4 mpd cards. Bonus/accelerated miles may be credited later.",
      important_exclusions: "Commonly excluded or risky: failing to meet S$1,000 annual SIA Group spend, spend outside UOB's accelerated categories, top-ups, quasi-cash, tax/government, insurance, utilities, education, hospitals/medical, financial institutions, crypto/securities and other UOB exclusions.",
      definitions_examples: "Accelerated categories are defined by UOB, not by user intention. Dining, food delivery, online shopping, online travel and transport must be recognised under UOB's category rules. Qualifying annual spend uses Singapore Airlines, Scoot and KrisShop wording on UOB's page; check the card terms for exact merchant scope.",
      simple_notes: "Use this for clients who hate juggling multiple cards or exceed 4 mpd caps often, especially if they regularly spend with SIA/Scoot/Kris+.",
      recommendation_tier: "Simple KrisFlyer direct-earn card",
      card_id: "krisflyer-uob",
      network: "Credit Card",
      category: "Miles",
      status: "Situational recommendation",
      base_earn_rate: "1.2 mpd on general spend.",
      rewards_currency: "KrisFlyer miles",
      expiry_or_crediting: "Miles are credited directly to KrisFlyer; accelerated miles timing follows UOB card terms.",
      recommended_pairings: "Recommend when client values simplicity or regularly exceeds specialised card caps.",
      official_product_url: "https://www.uob.com.sg/personal/cards/travel/krisflyer-card.page",
      official_terms_url: "https://www.uob.com.sg/personal/cards/travel/krisflyer-card.page",
      official_rewards_or_exclusions_url: "https://www.singaporeair.com/en_UK/sg/ppsclub-krisflyer/krisflyer/",
      research_reference_1: "https://milelion.com/2026/04/12/review-krisflyer-uob-credit-card/",
      research_reference_2: "https://suitesmile.com/best-uob-credit-cards-in-singapore/",
      last_verified: "2026-05-29",
      data_confidence: "High; official KrisFlyer UOB page reviewed 2026-05-29.",
      site_tags: "krisflyer,direct-miles,sia,high-spend,simplicity,uob",
    },
    {
      card_name: "OCBC Rewards Card",
      bank: "OCBC",
      earn_rate: "Promo: 6 mpd at selected merchants until 30 June 2026; usual selected retail earn can be 4 mpd.",
      use_card_for: "Shopee, Lazada, Taobao, TikTok Shop, Watsons and selected shopping/retail categories.",
      online_or_offline: "Mostly online shopping + selected retail.",
      monthly_bonus_limit: "Promo is roughly S$1,000 eligible spend/month based on OCBC$ bonus cap; recheck once promo ends.",
      cap_period: "Calendar month.",
      minimum_spend: "None for listed promo earning, subject to terms.",
      nuances: "Promo-dependent. Do not treat the 6 mpd rate as permanent. Merchant list and OCBC$ caps matter.",
      important_exclusions: "Commonly excluded or risky: spend outside selected merchants/categories, promo ending after 30 June 2026, transactions not coded under eligible retail MCCs, e-wallet/top-ups, cash advances, balance/fund transfers, tax/government, insurance, education, utilities, financial/quasi-cash and other OCBC rewards exclusions.",
      definitions_examples: "Selected merchant promo means only named merchants/platforms such as Watsons, Shopee, Lazada, Taobao and TikTok Shop count during the promo, subject to OCBC coding. Marketplace purchases can still depend on how the merchant/category is passed to OCBC.",
      simple_notes: "Use this as a shopping layer for clients who regularly buy from the listed merchants. Recheck after 30 June 2026.",
      recommendation_tier: "Promo / shopping recommendation",
      card_id: "ocbc-rewards",
      network: "Credit Card",
      category: "Miles",
      status: "Promo / shopping recommendation",
      base_earn_rate: "Base OCBC$ on eligible spend.",
      rewards_currency: "OCBC$",
      expiry_or_crediting: "OCBC$ expiry and redemption governed by OCBC$ Rewards Programme terms.",
      recommended_pairings: "Use as shopping layer beside Citi Rewards and DBS Woman's World.",
      official_product_url: "https://www.ocbc.com/personal-banking/cards/rewards-card",
      official_terms_url: "https://www.ocbc.com/iwov-resources/sg/ocbc/personal/pdf/cards/tnc-titaniumrewards-creditcard-programme-wef-1mar23.pdf",
      official_rewards_or_exclusions_url: "https://www.ocbc.com/personal-banking/cards/rewards-terms-and-conditions.html",
      research_reference_1: "https://milelion.com/2026/04/01/ocbc-rewards-card-offering-6-mpd-for-watsons-and-selected-e-commerce-platforms/",
      research_reference_2: "https://suitesmile.com/blog/2026/04/01/ocbc-rewards-card-promo-6-mpd-shopee-taobao-watsons/",
      last_verified: "2026-05-29",
      data_confidence: "High for current OCBC promo page; promo remains date-sensitive.",
      site_tags: "shopping,promo,watsons,shopee,lazada,taobao,tiktok,ocbc",
    },
  ],
  cashback: [
    {
      card_name: "Citi SMRT Card",
      bank: "Citibank",
      earn_rate: "5% SMRT$ savings on qualifying groceries, online purchases, Malaysian Ringgit spend and commute; 0.3% on retail spend.",
      use_card_for: "Groceries, online purchases, Malaysian Ringgit spend, taxis/ride-hailing and SimplyGo public transport.",
      online_or_offline: "Online + offline daily essentials.",
      monthly_bonus_limit: "Cashback/SMRT$ category caps are governed by Citi SMRT$ Rewards Program T&Cs.",
      cap_period: "Statement month.",
      minimum_spend: "S$500 minimum statement month spend for bonus rates; below that earns base 0.3% SMRT$ only.",
      nuances: "Better for clients who want simple savings instead of miles. Must hit minimum spend for headline savings rate.",
      important_exclusions: "Commonly excluded or risky: failing the S$500 statement-month minimum, mobile wallet transactions, travel-related online transactions, GrabPay/e-wallet top-ups, tax/government, insurance, education, utilities, financial/quasi-cash, securities/crypto, bill-payment platforms and other Citi rewards exclusions.",
      definitions_examples: "SMRT$ bonus categories are category/MCC based. Online purchases must not fall into Citi's excluded online categories. Commute/transport includes qualifying taxis, ride-hailing and SimplyGo/public transport style spend per Citi terms; wallet top-ups are not the same as transport spend.",
      simple_notes: "Use for cashback-first clients with groceries, online shopping, MYR spend or commute spend. Not a miles card.",
      recommendation_tier: "Daily essentials cashback card",
      card_id: "citi-smrt",
      network: "Visa",
      category: "Cashback",
      status: "Active recommendation",
      base_earn_rate: "0.3% SMRT$ on retail spend.",
      rewards_currency: "SMRT$",
      expiry_or_crediting: "SMRT$ redeemable for cash rebate or shopping vouchers per Citi terms.",
      recommended_pairings: "Use for clients who explicitly prefer cashback or have low/no interest in miles optimisation.",
      official_product_url: "https://www.citibank.com.sg/credit-cards/cashback/smrt-credit-card",
      official_terms_url: "https://www.citibank.com.sg/credit-cards/cashback/smrt-credit-card/pdf/citi-smrt-rewards-program.pdf",
      official_rewards_or_exclusions_url: "https://www.citibank.com.sg/credit-cards/cashback/smrt-credit-card/pdf/citi-smrt-rewards-program.pdf",
      research_reference_1: "https://www.singsaver.com.sg/credit-card/products/citi-smrt-card",
      research_reference_2: "https://www.moneysmart.sg/credit-cards/citi-smrt-card",
      last_verified: "2026-05-29",
      data_confidence: "High; official Citi SMRT page and SMRT$ rewards terms reviewed 2026-05-29.",
      site_tags: "cashback,groceries,online,transport,myr,citi",
    },
  ],
};
