const SHEET_CONFIG = {
  "spreadsheetId": "1PfwZpYRf6wBvcuCVZIfsUjxreO5Q8A_-OWbZJH3YRnk",
  "tabs": {
    "miles": "Miles",
    "cashback": "Cashback"
  }
};

const FALLBACK_CARDS = {
  "miles": [
    {
      "card_name": "HSBC Revolution Credit Card",
      "bank": "HSBC",
      "earn_rate": "4 mpd on eligible online/contactless bonus categories; up to 8 mpd with qualifying HSBC EGA setup.",
      "use_card_for": "Eligible dining, shopping, travel, ride-hailing, taxis, memberships and selected everyday online/contactless spend.",
      "online_or_offline": "Online + contactless, only within HSBC bonus categories.",
      "monthly_bonus_limit": "S$1,000/month for standard 4 mpd. EGA setup: about S$1,200/month eligible spend via 22,800 bonus points cap; check EGA conditions.",
      "cap_period": "Calendar month / HSBC qualifying posting basis.",
      "minimum_spend": "No minimum spend for standard 4 mpd. EGA boost requires qualifying HSBC Everyday Global Account setup.",
      "nuances": "Watch MCC/category eligibility. Good starter card, but EGA boost adds account/deposit/admin work.",
      "important_exclusions": "Excluded/risky: merchants outside HSBC bonus categories; e-wallet/stored-value top-ups; insurance; education/tuition; donations; government/tax; financial institutions; quasi-cash; securities/crypto; utilities/bills; professional services.",
      "definitions_examples": "Selected online spend = merchant processed as online and MCC is in HSBC's bonus list. Contactless = tap-to-pay at a terminal by card/mobile wallet. E-wallet top-ups are not contactless retail spend.",
      "simple_notes": "Use for eligible everyday online/contactless spend before moving overflow to Citi, DBS or UOB cards.",
      "recommendation_tier": "Core starter / flexible online-contactless",
      "card_id": "hsbc-revolution",
      "network": "Visa Signature",
      "category": "Miles",
      "status": "Active recommendation",
      "base_earn_rate": "Base points apply outside bonus eligibility.",
      "rewards_currency": "HSBC Reward points",
      "expiry_or_crediting": "Base points credited by statement cycle; bonus points by last day of following calendar month.",
      "recommended_pairings": "Pair with Citi Rewards or DBS Woman's World for online overflow; UOB Preferred Visa for mobile contactless clarity.",
      "official_product_url": "https://www.hsbc.com.sg/credit-cards/products/revolution/",
      "official_terms_url": "https://www.hsbc.com.sg/content/dam/hsbc/sg/documents/credit-cards/revolution/offers/revolution-credit-card-reward-points-terms-and-conditions.pdf",
      "official_rewards_or_exclusions_url": "https://www.hsbc.com.sg/credit-cards/products/revolution/",
      "research_reference_1": "https://milelion.com/2026/03/16/wow-hsbc-revolution-enhances-earn-rate-to-8-mpd-permanently-restores-travel-and-contactless-bonuses/",
      "research_reference_2": "https://suitesmile.com/blog/2026/04/08/hsbc-revolution-card-review/",
      "last_verified": "2026-05-29",
      "data_confidence": "High; official HSBC page and reward points terms reviewed 2026-05-29.",
      "site_tags": "starter,online,contactless,dining,travel,hsbc-ega"
    },
    {
      "card_name": "Citi Rewards Card",
      "bank": "Citibank",
      "earn_rate": "4 mpd via 10X Citi ThankYou Points on eligible online spend and selected shopping MCCs.",
      "use_card_for": "Online retail, food delivery, ride-hailing, online groceries, and selected department/clothing/shoe/bag shopping when MCC qualifies.",
      "online_or_offline": "Mainly online; selected offline shopping MCCs can qualify.",
      "monthly_bonus_limit": "S$1,000/statement month effective 10X cap, from the 9,000 Bonus Points cap.",
      "cap_period": "Statement month.",
      "minimum_spend": "No minimum spend for ordinary 10X earning.",
      "nuances": "Avoid travel and mobile-wallet routes. Citi excludes travel-related and mobile wallet transactions from 10X; track statement-month cap timing.",
      "important_exclusions": "Excluded/risky: flights; hotels; OTAs/travel agencies; cruises; mobile wallet transactions; Apple Pay/Google Pay in-app wallet routes; GrabPay/e-wallet top-ups; tax/government; insurance; education; utilities; financial/quasi-cash; crypto/securities; bill-payment platforms.",
      "definitions_examples": "Online spend = merchant processed as e-commerce. Mobile wallet transactions are not the same as direct online card payments; wallet top-ups/intermediary payments should be treated as risky or excluded.",
      "simple_notes": "Use for online retail, food delivery, ride-hailing and selected shopping. Do not use as the default card for flights, hotels or travel portals.",
      "recommendation_tier": "Online shopping workhorse",
      "card_id": "citi-rewards",
      "network": "Mastercard",
      "category": "Miles",
      "status": "Active recommendation",
      "base_earn_rate": "1X Citi ThankYou Point per S$1 on eligible base spend.",
      "rewards_currency": "Citi ThankYou Points",
      "expiry_or_crediting": "Subject to Citi ThankYou Rewards programme terms.",
      "recommended_pairings": "Pair with DBS Woman's World for broader online travel-type transactions; avoid using for excluded mobile-wallet routes.",
      "official_product_url": "https://www.citibank.com.sg/credit-cards/rewards/citi-rewards-card/",
      "official_terms_url": "https://www.citibank.com.sg/credit-cards/rewards/citi-rewards-card/pdf/10x-rewards-promotion-terms-and-conditions-2020.pdf",
      "official_rewards_or_exclusions_url": "https://www.citibank.com.sg/gcb/static/products_tncs",
      "research_reference_1": "https://milelion.com/2025/05/27/review-citi-rewards-credit-card/",
      "research_reference_2": "https://suitesmile.com/blog/2026/01/23/citi-rewards-card-review-best-miles-card/",
      "last_verified": "2026-05-29",
      "data_confidence": "High; official Citi card page and 10X terms reviewed 2026-05-29.",
      "site_tags": "online,shopping,food-delivery,ride-hailing,citi"
    },
    {
      "card_name": "DBS Woman's World Card",
      "bank": "DBS",
      "earn_rate": "4 mpd via 10X DBS Points on online spend; overseas spend earns 3X DBS Points / 1.2 mpd unless otherwise bonused.",
      "use_card_for": "Broad online spend, e-commerce, online travel bookings and website/app transactions.",
      "online_or_offline": "Online mainly; can be useful for overseas online spend depending on DBS rules.",
      "monthly_bonus_limit": "S$1,000/month eligible online spend cap.",
      "cap_period": "Calendar month.",
      "minimum_spend": "No minimum spend for bonus rate, subject to eligibility and cap.",
      "nuances": "Good broad online backup where Citi Rewards is excluded. DBS Points from this card have short expiry; income requirement is higher than mass-market cards.",
      "important_exclusions": "Excluded/risky: transactions DBS does not recognise as online retail; physical in-store spend; cash advances; balance/fund transfers; fees/charges; tax/government; insurance; education; utilities; top-ups; financial/quasi-cash; securities/crypto; other DBS rewards exclusions.",
      "definitions_examples": "Online purchase = merchant/acquirer processes it as online. Website/app checkout is intended; physical tap/in-store spend normally is not. Online travel may work better here than Citi Rewards, but still depends on DBS bonus rules and merchant coding.",
      "simple_notes": "Use for online spend where Citi Rewards is excluded, especially online travel-style transactions if DBS awards bonus points.",
      "recommendation_tier": "Broad online spend card",
      "card_id": "dbs-womans-world",
      "network": "Mastercard",
      "category": "Miles",
      "status": "Active recommendation",
      "base_earn_rate": "1X DBS Point per S$5 local spend and 3X DBS Points per S$5 overseas spend, unless bonus applies.",
      "rewards_currency": "DBS Points",
      "expiry_or_crediting": "DBS Points from Woman's World are generally short-expiry; verify current DBS rewards terms before redemption planning.",
      "recommended_pairings": "Pair with Citi Rewards for online cap stacking; use UOB Preferred Visa or Visa Signature for offline mobile contactless.",
      "official_product_url": "https://www.dbs.com.sg/personal/cards/credit-cards/dbs-woman-mastercard-card",
      "official_terms_url": "https://www.dbs.com.sg/personal/cards/cards-terms-conditions.page",
      "official_rewards_or_exclusions_url": "https://www.dbs.com.sg/personal/cards/cards-faqs.page",
      "research_reference_1": "https://milelion.com/2025/08/09/review-dbs-womans-world-card/",
      "research_reference_2": "https://mainlymiles.com/2025/08/07/dbs-wwmc-review-2025/",
      "last_verified": "2026-05-29",
      "data_confidence": "High; official DBS product page reviewed 2026-05-29.",
      "site_tags": "online,travel,ecommerce,dbs,high-income"
    },
    {
      "card_name": "UOB Lady's Card",
      "bank": "UOB",
      "earn_rate": "4 mpd via UNI$10 per S$5 on selected Lady's Card rewards category/categories.",
      "use_card_for": "The user's biggest chosen category: Fashion, Dining, Travel, Beauty & Wellness, Family, Transport or Entertainment.",
      "online_or_offline": "Online or offline, as long as the selected category MCC qualifies.",
      "monthly_bonus_limit": "S$1,000/month selected-category cap for mass-market UOB Lady's Card. Solitaire variants have higher/different caps.",
      "cap_period": "Calendar month.",
      "minimum_spend": "No minimum spend for selected-category earn. Savings-account boost has separate deposit criteria.",
      "nuances": "Pick the category before spending and review quarterly. UOB awards UNI$ in S$5 blocks, so odd amounts can lose value. MCC matters more than store description.",
      "important_exclusions": "Excluded/risky: spend outside chosen category; wrong MCC despite similar-looking merchant; top-ups; quasi-cash; tax/government; insurance; utilities; education; hospitals/medical; financial institutions; crypto/securities; other UOB exclusions.",
      "definitions_examples": "Selected category = MCC-based, not based on user intent. A hotel cafe, marketplace seller or Taobao merchant may code differently. UOB awards in S$5 blocks, so small odd transaction amounts may earn less than expected.",
      "simple_notes": "Use as the dedicated card for the user's biggest recurring category, such as dining, family/groceries, transport or travel.",
      "recommendation_tier": "Choose-one-category optimiser",
      "card_id": "uob-ladys",
      "network": "Mastercard",
      "category": "Miles",
      "status": "Active recommendation",
      "base_earn_rate": "UNI$1 per S$5 on other eligible spend.",
      "rewards_currency": "UNI$",
      "expiry_or_crediting": "Bonus UNI$ credited per UOB terms; UNI$ expiry applies.",
      "recommended_pairings": "Use as the deliberate category card beside Citi Rewards / DBS Woman's World / UOB Preferred Visa.",
      "official_product_url": "https://www.uob.com.sg/ladys",
      "official_terms_url": "https://www.uob.com.sg/assets/pdfs/ladys-cards-tcs.pdf",
      "official_rewards_or_exclusions_url": "https://www.uob.com.sg/personal/cards/rewards/ladys-card/index.page",
      "research_reference_1": "https://milelion.com/2026/03/09/uob-ladys-card-lucky-draw-win-76000-bonus-miles-or-s500-gift-cards/",
      "research_reference_2": "https://suitesmile.com/best-miles-credit-cards-singapore/",
      "last_verified": "2026-05-29",
      "data_confidence": "Medium-high; selected-category cap wording should be rechecked against UOB card-specific T&Cs before user advice.",
      "site_tags": "category,dining,family,travel,transport,uob"
    },
    {
      "card_name": "UOB Preferred Visa Card",
      "bank": "UOB",
      "earn_rate": "4 mpd via UNI$10 per S$5 on selected online transactions and mobile contactless transactions.",
      "use_card_for": "Apple Pay/Google Pay/Samsung Pay taps, selected online shopping/entertainment, and eligible SimplyGo.",
      "online_or_offline": "Offline via mobile contactless; selected online transactions also qualify.",
      "monthly_bonus_limit": "S$600/month selected online + S$600/month mobile contactless, or S$1,200/month total if both buckets are used. From 1 Oct 2025, bonus UNI$ cap is UNI$1,080 per category / UNI$2,160 total.",
      "cap_period": "Calendar month.",
      "minimum_spend": "No minimum spend for bonus earn under current terms.",
      "nuances": "Use mobile wallet tap for the contactless bucket; physical card tap does not count for that bucket. UOB awards UNI$ in S$5 blocks. Online and mobile contactless have separate caps.",
      "important_exclusions": "Excluded/risky: physical card tap for contactless bucket; non-selected online merchants; in-app wallet/top-up transactions; GrabPay/e-wallet top-ups; tax/government; insurance; education; utilities; hospitals/medical; financial institutions; quasi-cash; crypto/securities; other UOB exclusions.",
      "definitions_examples": "Mobile contactless = add card to Apple Pay/Google Pay/Samsung Pay or approved mobile wallet, then tap phone/watch at Visa contactless reader. Physical card Visa payWave is not the same for this card. Selected online must fall within UOB's online categories.",
      "simple_notes": "Use as the default offline Apple Pay/Google Pay card, then use the selected online bucket separately.",
      "recommendation_tier": "Mobile contactless default",
      "card_id": "uob-preferred-visa",
      "network": "Visa",
      "category": "Miles",
      "status": "Active recommendation",
      "base_earn_rate": "UNI$1 per S$5 on other eligible spend.",
      "rewards_currency": "UNI$",
      "expiry_or_crediting": "Bonus UNI$ governed by UOB Preferred Visa terms.",
      "recommended_pairings": "Pair with UOB Visa Signature for larger contactless/overseas buckets or with UOB Lady's for category spend.",
      "official_product_url": "https://www.uob.com.sg/personal/cards/rewards/preferred-visa-card.page",
      "official_terms_url": "https://www.uob.com.sg/web-resources/personal/pdf/personal/cards/credit-cards/rewards-cards/uob-preferred-platinum-visa-card/terms-and-conditions-for-preferred-plat-visa.pdf",
      "official_rewards_or_exclusions_url": "https://www.uob.com.sg/personal/cards/card-privileges/uob-dollar.page",
      "research_reference_1": "https://milelion.com/2026/03/29/review-uob-preferred-platinum-visa-card/",
      "research_reference_2": "https://suitesmile.com/blog/2026/03/10/uob-preferred-visa-card-refresh-new-name-new-look/",
      "last_verified": "2026-05-29",
      "data_confidence": "High; official UOB Preferred Visa page and 2026 MileLion interpretation reviewed 2026-05-29.",
      "site_tags": "mobile-contactless,online,simplygo,uob,everyday"
    },
    {
      "card_name": "UOB Visa Signature Card",
      "bank": "UOB",
      "earn_rate": "4 mpd via UNI$10 per S$5 on overseas foreign-currency spend and qualifying local petrol/contactless spend.",
      "use_card_for": "Overseas foreign-currency transactions, local petrol, larger local contactless spend and eligible SimplyGo.",
      "online_or_offline": "Offline contactless plus overseas online/offline spend, subject to category rules.",
      "monthly_bonus_limit": "S$1,000 minimum + about S$1,200 cap per bucket per statement period. Buckets: overseas spend; local petrol/contactless.",
      "cap_period": "Statement period.",
      "minimum_spend": "S$1,000 minimum spend in the relevant bucket.",
      "nuances": "Threshold card: only use when the user can clear the S$1,000 bucket minimum. UOB awards UNI$ in S$5 blocks. Strong for higher-spend months, poor for casual small spend.",
      "important_exclusions": "Excluded/risky: missing S$1,000 bucket minimum; non-contactless transactions; non-petrol MCCs for petrol bucket; SGD overseas/foreign-gateway ambiguity; top-ups; quasi-cash; tax/government; insurance; utilities; hospitals/medical; financial institutions; other UOB exclusions.",
      "definitions_examples": "Contactless = Visa payWave using physical card or approved mobile wallet tap at a Visa payWave reader. UOB also treats SimplyGo ABT as contactless under current rules. Magnetic Secure Transmission and non-contactless payment flows are excluded.",
      "simple_notes": "Use for bigger contactless, petrol or overseas-spend months when the user can confidently cross the S$1,000 bucket minimum.",
      "recommendation_tier": "Higher-cap contactless / overseas card",
      "card_id": "uob-visa-signature",
      "network": "Visa Signature",
      "category": "Miles",
      "status": "Active recommendation",
      "base_earn_rate": "UNI$1 per S$5 on other eligible spend.",
      "rewards_currency": "UNI$",
      "expiry_or_crediting": "Bonus UNI$ credited in following statement period.",
      "recommended_pairings": "Use after UOB Preferred Visa cap or for overseas spend; not ideal for low-spend users.",
      "official_product_url": "https://www.uob.com.sg/personal/cards/rewards/visa-signature-card.page",
      "official_terms_url": "https://www.uob.com.sg/web-resources/personal/pdf/personal/cards/credit-cards/travel-cards/uob-visa-signature-card/terms-and-conditions-governing-uob-visa-signature-card.pdf",
      "official_rewards_or_exclusions_url": "https://www.uob.com.sg/personal/cards/card-privileges/uob-dollar.page",
      "research_reference_1": "https://milelion.com/2025/08/29/review-uob-visa-signature-card/",
      "research_reference_2": "https://suitesmile.com/best-uob-credit-cards-in-singapore/",
      "last_verified": "2026-05-29",
      "data_confidence": "High; official UOB Visa Signature terms reviewed 2026-05-29.",
      "site_tags": "contactless,overseas,petrol,simplygo,uob,higher-cap"
    },
    {
      "card_name": "KrisFlyer UOB Credit Card",
      "bank": "UOB",
      "earn_rate": "3 mpd on SIA/Scoot/KrisShop/Kris+/Pelago; 2.4 mpd on selected categories after S$1,000 annual SIA Group spend; 1.2 mpd general.",
      "use_card_for": "SIA Group spend, dining, food delivery, online shopping, online travel and transport.",
      "online_or_offline": "Online + offline, depending on category.",
      "monthly_bonus_limit": "Not a 4 mpd card; no 4 mpd cap. 3 mpd SIA/Kris+ earn and 2.4 mpd accelerated categories are subject to UOB terms.",
      "cap_period": "Card year / annual qualification for accelerated categories.",
      "minimum_spend": "S$1,000 annual Singapore Airlines / Scoot / KrisShop qualifying spend to unlock accelerated everyday categories.",
      "nuances": "Simple direct-to-KrisFlyer option, but lower earn than specialised 4 mpd cards. Bonus/accelerated miles may be credited later.",
      "important_exclusions": "Excluded/risky: failing S$1,000 annual SIA Group spend; spend outside UOB accelerated categories; top-ups; quasi-cash; tax/government; insurance; utilities; education; hospitals/medical; financial institutions; crypto/securities; other UOB exclusions.",
      "definitions_examples": "Accelerated categories = UOB-defined categories, not user intention. Dining, food delivery, online shopping, online travel and transport must be recognised under UOB rules. Qualifying annual spend uses Singapore Airlines, Scoot and KrisShop wording; check terms for exact merchant scope.",
      "simple_notes": "Use when the user values simplicity, wants direct KrisFlyer miles, or regularly exceeds specialised 4 mpd card caps.",
      "recommendation_tier": "Simple KrisFlyer direct-earn card",
      "card_id": "krisflyer-uob",
      "network": "Credit Card",
      "category": "Miles",
      "status": "Situational recommendation",
      "base_earn_rate": "1.2 mpd on general spend.",
      "rewards_currency": "KrisFlyer miles",
      "expiry_or_crediting": "Miles are credited directly to KrisFlyer; accelerated miles timing follows UOB card terms.",
      "recommended_pairings": "Recommend when user values simplicity or regularly exceeds specialised card caps.",
      "official_product_url": "https://www.uob.com.sg/personal/cards/travel/krisflyer-card.page",
      "official_terms_url": "https://www.uob.com.sg/personal/cards/travel/krisflyer-card.page",
      "official_rewards_or_exclusions_url": "https://www.singaporeair.com/en_UK/sg/ppsclub-krisflyer/krisflyer/",
      "research_reference_1": "https://milelion.com/2026/04/12/review-krisflyer-uob-credit-card/",
      "research_reference_2": "https://suitesmile.com/best-uob-credit-cards-in-singapore/",
      "last_verified": "2026-05-29",
      "data_confidence": "High; official KrisFlyer UOB page reviewed 2026-05-29.",
      "site_tags": "krisflyer,direct-miles,sia,high-spend,simplicity,uob"
    },
    {
      "card_name": "OCBC Rewards Card",
      "bank": "OCBC",
      "earn_rate": "Promo: 6 mpd at selected merchants/platforms; usual selected retail earn can be 4 mpd.",
      "use_card_for": "Watsons, Shopee, Lazada, Taobao, TikTok Shop and selected shopping/retail categories.",
      "online_or_offline": "Mostly online shopping + selected retail.",
      "monthly_bonus_limit": "About S$1,000/month eligible promo spend, based on bonus cap. Recheck current promo terms and end date.",
      "cap_period": "Calendar month.",
      "minimum_spend": "No minimum spend for listed promo earning, subject to terms.",
      "nuances": "Promo-dependent. Use only for named merchants/categories and recheck whenever the campaign changes. Merchant list, MCC and OCBC$ caps matter.",
      "important_exclusions": "Excluded/risky: spend outside selected merchants/categories; promo period ending/changing; transactions not coded under eligible retail MCCs; e-wallet/top-ups; cash advances; balance/fund transfers; tax/government; insurance; education; utilities; financial/quasi-cash; other OCBC rewards exclusions.",
      "definitions_examples": "Selected merchant promo = named merchants/platforms such as Watsons, Shopee, Lazada, Taobao and TikTok Shop, subject to OCBC coding. Marketplace purchases still depend on how merchant/category data is passed to OCBC.",
      "simple_notes": "Use as a shopping layer for users who regularly buy from listed merchants. Recheck before recommending after any promo date change.",
      "recommendation_tier": "Promo / shopping recommendation",
      "card_id": "ocbc-rewards",
      "network": "Credit Card",
      "category": "Miles",
      "status": "Promo / shopping recommendation",
      "base_earn_rate": "Base OCBC$ on eligible spend.",
      "rewards_currency": "OCBC$",
      "expiry_or_crediting": "OCBC$ expiry and redemption governed by OCBC$ Rewards Programme terms.",
      "recommended_pairings": "Use as shopping layer beside Citi Rewards and DBS Woman's World.",
      "official_product_url": "https://www.ocbc.com/personal-banking/cards/rewards-card",
      "official_terms_url": "https://www.ocbc.com/iwov-resources/sg/ocbc/personal/pdf/cards/tnc-titaniumrewards-creditcard-programme-wef-1mar23.pdf",
      "official_rewards_or_exclusions_url": "https://www.ocbc.com/personal-banking/cards/rewards-terms-and-conditions.html",
      "research_reference_1": "https://milelion.com/2026/04/01/ocbc-rewards-card-offering-6-mpd-for-watsons-and-selected-e-commerce-platforms/",
      "research_reference_2": "https://suitesmile.com/blog/2026/04/01/ocbc-rewards-card-promo-6-mpd-shopee-taobao-watsons/",
      "last_verified": "2026-05-29",
      "data_confidence": "High for current OCBC promo page; promo remains date-sensitive.",
      "site_tags": "shopping,promo,watsons,shopee,lazada,taobao,tiktok,ocbc"
    }
  ],
  "cashback": [
    {
      "card_name": "Citi SMRT Card",
      "bank": "Citibank",
      "earn_rate": "5% SMRT$ on qualifying groceries, online, Malaysian Ringgit spend and commute after S$500 statement-month spend; 0.3% base.",
      "use_card_for": "Groceries, online purchases, Malaysian Ringgit spend, taxis/ride-hailing and SimplyGo public transport.",
      "online_or_offline": "Online + offline daily essentials.",
      "monthly_bonus_limit": "S$500/statement month minimum for 5% bonus categories. Category caps and eligibility follow Citi SMRT$ Rewards Program T&Cs.",
      "cap_period": "Statement month.",
      "minimum_spend": "S$500 minimum statement-month spend for bonus rates; below that earns base 0.3% SMRT$ only.",
      "nuances": "Good cashback-first card, but only if the user reliably hits S$500/month. Online and commute categories still depend on Citi category/MCC rules.",
      "important_exclusions": "Excluded/risky: missing S$500 statement-month minimum; mobile wallet transactions; travel-related online transactions; GrabPay/e-wallet top-ups; tax/government; insurance; education; utilities; financial/quasi-cash; securities/crypto; bill-payment platforms; other Citi rewards exclusions.",
      "definitions_examples": "SMRT$ bonus categories = category/MCC based. Online purchases must avoid Citi's excluded online categories. SimplyGo = tapping the Citi SMRT Card/mobile wallet/wearable for bus/train rides; wallet top-ups are not transport spend.",
      "simple_notes": "Use for cashback-first users with groceries, online shopping, MYR spend or commute spend. Not a miles card.",
      "recommendation_tier": "Daily essentials cashback card",
      "card_id": "citi-smrt",
      "network": "Visa",
      "category": "Cashback",
      "status": "Active recommendation",
      "base_earn_rate": "0.3% SMRT$ on retail spend.",
      "rewards_currency": "SMRT$",
      "expiry_or_crediting": "SMRT$ redeemable for cash rebate or shopping vouchers per Citi terms.",
      "recommended_pairings": "Use for users who explicitly prefer cashback or have low/no interest in miles optimisation.",
      "official_product_url": "https://www.citibank.com.sg/credit-cards/cashback/smrt-credit-card",
      "official_terms_url": "https://www.citibank.com.sg/credit-cards/cashback/smrt-credit-card/pdf/citi-smrt-rewards-program.pdf",
      "official_rewards_or_exclusions_url": "https://www.citibank.com.sg/credit-cards/cashback/smrt-credit-card/pdf/citi-smrt-rewards-program.pdf",
      "research_reference_1": "https://www.singsaver.com.sg/credit-card/products/citi-smrt-card",
      "research_reference_2": "https://thefinance.sg/2026/02/21/updated-citi-smrt-review/",
      "last_verified": "2026-05-29",
      "data_confidence": "High; official Citi SMRT page and SMRT$ rewards terms reviewed 2026-05-29.",
      "site_tags": "cashback,groceries,online,transport,myr,citi"
    }
  ]
};
